// Code generated by go generate; DO NOT EDIT.
// This file was generated by github.com/kirill-zak/go-env/cmd/gen.
// Sources:
package example

import (
	"time"

	envPkg "github.com/kirill-zak/go-env/pkg/env"
)

// CheckBatchSizeDefault is a default value for check_batch_size variable.
const CheckBatchSizeDefault = 1000

// GetCheckBatchSize uses global Env to get check_batch_size and returns CheckBatchSizeDefault if the lookup fails.
// Default value: 1000
// Description: Check batch size
//
// Env variables are searched in the following order:
//   - {envPrefix}_CHECK_BATCH_SIZE
//   - CHECK_BATCH_SIZE
func GetCheckBatchSize() int {
	envValue, err := LookupCheckBatchSize()
	if err != nil {
		return CheckBatchSizeDefault
	}

	return envValue
}

// LookupCheckBatchSize uses global Env to get check_batch_size.
// It returns wrapped ErrEnvNotExists error unless env was set.
// It returns an error if the value of the env variable is of the wrong type.
// See GetCheckBatchSize for more info.
func LookupCheckBatchSize() (int, error) {
	envValue, err := envPkg.GetGlobal().LookupWithErr("check_batch_size", []string{"CHECK_BATCH_SIZE"})
	if err != nil {
		return *new(int), err
	}

	_, parsed, err := envPkg.AsGoType("int", envValue)
	if err != nil {
		return *new(int), err
	}

	return parsed.(int), nil
}

// CheckIntervalDefault is a default value for check_interval variable.
const CheckIntervalDefault = time.Duration(600000000000)

// GetCheckInterval uses global Env to get check_interval and returns CheckIntervalDefault if the lookup fails.
// Default value: 10m0s
// Description: Check interval
//
// Env variables are searched in the following order:
//   - {envPrefix}_CHECK_INTERVAL
//   - CHECK_INTERVAL
func GetCheckInterval() time.Duration {
	envValue, err := LookupCheckInterval()
	if err != nil {
		return CheckIntervalDefault
	}

	return envValue
}

// LookupCheckInterval uses global Env to get check_interval.
// It returns wrapped ErrEnvNotExists error unless env was set.
// It returns an error if the value of the env variable is of the wrong type.
// See GetCheckInterval for more info.
func LookupCheckInterval() (time.Duration, error) {
	envValue, err := envPkg.GetGlobal().LookupWithErr("check_interval", []string{"CHECK_INTERVAL"})
	if err != nil {
		return *new(time.Duration), err
	}

	_, parsed, err := envPkg.AsGoType("duration", envValue)
	if err != nil {
		return *new(time.Duration), err
	}

	return parsed.(time.Duration), nil
}

// CheckScheduleDefault is a default value for check_schedule variable.
const CheckScheduleDefault = "* * 2-6 * * * *"

// GetCheckSchedule uses global Env to get check_schedule and returns CheckScheduleDefault if the lookup fails.
// Default value: "* * 2-6 * * * *"
// Description: Check schedule
//
// Env variables are searched in the following order:
//   - {envPrefix}_CHECK_SCHEDULE
//   - CHECK_SCHEDULE
func GetCheckSchedule() string {
	envValue, err := LookupCheckSchedule()
	if err != nil {
		return CheckScheduleDefault
	}

	return envValue
}

// LookupCheckSchedule uses global Env to get check_schedule.
// It returns wrapped ErrEnvNotExists error unless env was set.
// It returns an error if the value of the env variable is of the wrong type.
// See GetCheckSchedule for more info.
func LookupCheckSchedule() (string, error) {
	envValue, err := envPkg.GetGlobal().LookupWithErr("check_schedule", []string{"CHECK_SCHEDULE"})
	if err != nil {
		return *new(string), err
	}

	_, parsed, err := envPkg.AsGoType("string", envValue)
	if err != nil {
		return *new(string), err
	}

	return parsed.(string), nil
}
