package templating

import (
	htmlTemplate "html/template"
	"strings"
	"text/template"
)

// fileHeaderTemplate is a text template that creates imports block and helper functions.
//
// Required input fields:
//
//	PackageName - string
var fileHeaderTemplate = template.Must(template.New("").
	Funcs(template.FuncMap{"StringsJoin": strings.Join}).
	Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated by github.com/kirill-zak/go-env/cmd/gen.
// Sources: {{ StringsJoin .Sources ";" }}
package {{ .PackageName }}

{{ if .NeedImport }}import envPkg "github.com/kirill-zak/go-env/pkg/env"{{ end }}
`))

// basicGetterTemplate is a text template for obtaining single env variable.
// Required input fields:
//
//	VariableName - string
//	VariableDefaultValue - interface{}
//	EnvNames - []string
//	Description - string
//	GoType - string.
var basicGetterTemplate = template.Must(template.New("").
	Funcs(template.FuncMap{"asConstValue": asConstValue}).
	Funcs(template.FuncMap{"toCamelCase": snakeToCamel}).
	Funcs(template.FuncMap{"formatEnvListInComment": formatEnvListInComment}).
	Funcs(template.FuncMap{"canBeConst": canBeConst}).
	Funcs(template.FuncMap{"prettyValue": prettyValue}).
	Parse(`{{ $defaultVarName := (print (toCamelCase .VariableName) "Default") }}
// {{ $defaultVarName }} is a default value for {{ .VariableName }} variable.
{{ if canBeConst .VariableDefaultValue }}const{{ else }}var{{ end }} {{ $defaultVarName }} = {{ asConstValue .VariableDefaultValue }}

// Get{{ toCamelCase .VariableName }} uses global Env to get {{ .VariableName }} and returns {{ $defaultVarName }} if the lookup fails.
// Default value: {{ .VariableDefaultValue | prettyValue }}
// Description: {{ .VariableDescription }}
//
// Env variables are searched in the following order:
{{ formatEnvListInComment .EnvNames }}
func Get{{ toCamelCase .VariableName }}() {{ .GoType }} {
	envValue, err := Lookup{{ toCamelCase .VariableName }}()
	if err != nil {
		return {{ $defaultVarName }}
	}

	return envValue
}

// Lookup{{ toCamelCase .VariableName }} uses global Env to get {{ .VariableName }}.
// It returns wrapped ErrEnvNotExists error unless env was set.
// It returns an error if the value of the env variable is of the wrong type.
// See Get{{ toCamelCase .VariableName }} for more info.
func Lookup{{ toCamelCase .VariableName }}() ({{ .GoType }}, error) {
	envValue, err := envPkg.GetGlobal().LookupWithErr({{ asConstValue .VariableName }}, {{ asConstValue .EnvNames }})
	if err != nil {
		return *new({{ .GoType }}), err
	}

	_, parsed, err := envPkg.AsGoType({{ asConstValue .VariableType }}, envValue)
	if err != nil {
		return *new({{ .GoType }}), err
	}

	{{ if gt (len .Rules) 0 }}
	err = envPkg.Validate({{ asConstValue .Rules }}, parsed.({{ .GoType }}), {{ asConstValue .Critical }})
	if err != nil {
		return *new({{ .GoType }}), err
	}
	{{- end }}

	return parsed.({{ .GoType }}), nil
}
`))

// basicHTMLTemplate is a text template for obtaining single env variable.
// Required input fields:
//
//	 Name - string
//	 Variables - []Variable
//		EnvNames - []string
//		Type - string
//	    Default - interface{}
//	    Description - string
//	    Comment - string.
var basicHTMLTemplate = htmlTemplate.Must(htmlTemplate.New("").
	Funcs(htmlTemplate.FuncMap{"prettyValue": prettyValue}).
	Parse(`# Environment Variables
<table class="env-vars">
	<tbody>
		{{- range . }}
		{{- if ne .Name "" }}
		<tr>
			<th class="env-vars-section-name" colspan="5">{{ .Name }}</th>
		</tr>
		{{- end }}
		<tr class="env-vars-section-header">
			<th>Переменная</th>
			<th>Тип</th>
			<th>Ограничения</th>
			<th>Значение по умолчанию</th>
			<th>Описание</th>
		</tr>
		{{- range .Variables }}
		<tr>
			<td>
				{{- range $i, $e := .EnvNames -}}
					{{- if ne $i 0 }}<br>{{ end -}}
					{{- $e -}}
				{{- end -}}
			</td>
			<td><code>{{ .Type }}</code></td>
			{{- if gt (len .Rules) 0 }}
			<td>
				{{ if .Critical }}<b>Строгие:</b><br>{{ else }}<b>Нестрогие:</b><br>{{ end }}
				{{- range $i, $e := .Rules -}}
					{{- if ne $i 0 }}<br>{{ end -}}
					{{- $e -}}
				{{- end }}
			</td>
			{{- else }}
			<td>—</td>
			{{- end }}
			<td><code>{{ .Default | prettyValue }}</code></td>
			<td>
				<p>{{ .Description }}</p>
				{{- if ne .Comment "" }}
				<p><small>{{ .Comment }}</small></p>
				{{- end }}
			</td>
		</tr>
		{{- end }}
		{{- end }}
	</tbody>
</table>
`))
